version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/docker/python-opencv/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/docker/hdr-tools/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
#  - package-ecosystem: "pip"
#    directory: "/docker/python-opencv/"
#    schedule:
#      interval: "daily"
#    ignore:
#      - dependency-name: "numpy"
#    groups:
#      pip:
#        patterns:
#        - '*'
