name: Publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  LIBJXL_VERSION: v0.10.2
  IMAGEMAGICK_VERSION: 7.1.1-32
  LIBULTRAHDR_GIT_TAG: 1.0.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

jobs:
  build_hdr_tools:
    name: Push hdr-tools Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args:
            - IM_GIT_TAG=${{ env.IMAGEMAGICK_VERSION }}
            - LIBULTRAHDR_GIT_TAG=${{ env.LIBULTRAHDR_GIT_TAG }}
          tags: |
            ghcr.io/cmahnke/hdr-tools:imagemagick-${{ env.IMAGEMAGICK_VERSION }}-uhdr-${{ env.LIBULTRAHDR_GIT_TAG }}

  build_hdr_tools-latest:
    name: Push hdr-tools Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      LIBJXL_VERSION: v0.10.2
      IMAGEMAGICK_VERSION: main
      LIBULTRAHDR_GIT_TAG: main
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args:
            - IM_GIT_TAG=${{ env.IMAGEMAGICK_VERSION }}
            - LIBULTRAHDR_GIT_TAG=${{ env.LIBULTRAHDR_GIT_TAG }}
          tags: |
            ghcr.io/cmahnke/hdr-tools:latest
            ghcr.io/cmahnke/hdr-tools:imagemagick-${{ env.IMAGEMAGICK_VERSION }}-uhdr-${{ env.LIBULTRAHDR_GIT_TAG }}
